name: CoreAttackPVP
version: '${project.version}'
main: mochineko.core_attack_pvp.Main
api-version: '1.20'

commands:
  game_start:
    description: "ゲームを開始するコマンド"
    permission: game_start
  game_team:
    description: "チームに関するコマンド"
    permission: game_team
  admin:
    description: "運営モードになるコマンド"
    permission: admin
  kit:
    description: "キットに関するコマンド"
    permission: kit
  set_gametime:
    description: "ゲームの時間に関するコマンド"
    permission: set_gametime